name: Health check

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://render-test-o6j7.onrender.com/jfwfih
      - name: Discord Webhook Notify Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ failure() }}
        with:
          severity: error
          details: Build failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
